services:
  # 1. PostgreSQL Database Service
  pdns-db:
    image: postgres:16
    container_name: pdns-db
    restart: unless-stopped
    networks:
      - pdns-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=powerdns
      - POSTGRES_USER=powerdns
      - POSTGRES_PASSWORD=powerdns

  # 2. PowerDNS Authoritative Server Service
  pdns-auth:
    image: powerdns/pdns-auth-master
    container_name: pdns-auth
    restart: unless-stopped
    networks:
      pdns-net:
        # Assign a static IP to this container
        ipv4_address: 172.28.0.10
    volumes:
      - ./pdns-auth/pdns.conf:/etc/powerdns/pdns.conf:ro
      - pdns-run:/var/run/pdns
    command:
      - --config-dir=/etc/powerdns
      - --socket-dir=/var/run/pdns
    ports:
      - "8081:8081"
    depends_on:
      - pdns-db

  # 3. PowerDNS Recursor Service
  pdns-recursor:
    image: powerdns/pdns-recursor-51 
    container_name: pdns-recursor
    restart: unless-stopped
    networks:
      - pdns-net
    depends_on:
      - pdns-auth
    volumes:
      - ./pdns-recursor/recursor.yml:/etc/powerdns/recursor.yml:ro
      - pdns-run:/var/run/pdns
    command:
      - --config-dir=/etc/powerdns
      - --socket-dir=/var/run/pdns

  # 4. dnsdist Service (Public Entrypoint)
  dnsdist:
    image: powerdns/dnsdist-19
    container_name: dnsdist
    restart: unless-stopped
    networks:
      - pdns-net
    depends_on:
      - pdns-recursor
    ports:
      # Map the standard DNS ports from the host to the container.
      - "53:53/udp"
      - "53:53/tcp"
      # Expose the dnsdist web interface/API port.
      - "8083:8083"
    volumes:
      - ./dnsdist/dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro

networks:
  pdns-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

volumes:
  postgres-data:
    name: postgres-data
  pdns-run: {}
