all:
  children:
    kafka:
      hosts:
        node-powerdns-01:
          ansible_host: 192.168.56.53
  vars:
    # tell every SSH connection in this play to skip host‑key checking
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_user: vagrant
